# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/workspace/DataVisualizer/DataVisualizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/workspace/DataVisualizer/DataVisualizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/workspace/DataVisualizer/DataVisualizer/CMakeFiles /home/martin/workspace/DataVisualizer/DataVisualizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/workspace/DataVisualizer/DataVisualizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Template

# Build rule for target.
Template: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Template
.PHONY : Template

# fast build rule for target.
Template/fast:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/build
.PHONY : Template/fast

# Manual pre-install relink rule for target.
Template/preinstall:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/preinstall
.PHONY : Template/preinstall

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f test/test1/CMakeFiles/main.dir/build.make test/test1/CMakeFiles/main.dir/build
.PHONY : main/fast

src/Basic2DLinePlot.o: src/Basic2DLinePlot.cpp.o

.PHONY : src/Basic2DLinePlot.o

# target to build an object file
src/Basic2DLinePlot.cpp.o:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/Basic2DLinePlot.cpp.o
.PHONY : src/Basic2DLinePlot.cpp.o

src/Basic2DLinePlot.i: src/Basic2DLinePlot.cpp.i

.PHONY : src/Basic2DLinePlot.i

# target to preprocess a source file
src/Basic2DLinePlot.cpp.i:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/Basic2DLinePlot.cpp.i
.PHONY : src/Basic2DLinePlot.cpp.i

src/Basic2DLinePlot.s: src/Basic2DLinePlot.cpp.s

.PHONY : src/Basic2DLinePlot.s

# target to generate assembly for a file
src/Basic2DLinePlot.cpp.s:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/Basic2DLinePlot.cpp.s
.PHONY : src/Basic2DLinePlot.cpp.s

src/DataSet.o: src/DataSet.cpp.o

.PHONY : src/DataSet.o

# target to build an object file
src/DataSet.cpp.o:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataSet.cpp.o
.PHONY : src/DataSet.cpp.o

src/DataSet.i: src/DataSet.cpp.i

.PHONY : src/DataSet.i

# target to preprocess a source file
src/DataSet.cpp.i:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataSet.cpp.i
.PHONY : src/DataSet.cpp.i

src/DataSet.s: src/DataSet.cpp.s

.PHONY : src/DataSet.s

# target to generate assembly for a file
src/DataSet.cpp.s:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataSet.cpp.s
.PHONY : src/DataSet.cpp.s

src/DataSets.o: src/DataSets.cpp.o

.PHONY : src/DataSets.o

# target to build an object file
src/DataSets.cpp.o:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataSets.cpp.o
.PHONY : src/DataSets.cpp.o

src/DataSets.i: src/DataSets.cpp.i

.PHONY : src/DataSets.i

# target to preprocess a source file
src/DataSets.cpp.i:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataSets.cpp.i
.PHONY : src/DataSets.cpp.i

src/DataSets.s: src/DataSets.cpp.s

.PHONY : src/DataSets.s

# target to generate assembly for a file
src/DataSets.cpp.s:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataSets.cpp.s
.PHONY : src/DataSets.cpp.s

src/DataVisualizer.o: src/DataVisualizer.cpp.o

.PHONY : src/DataVisualizer.o

# target to build an object file
src/DataVisualizer.cpp.o:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataVisualizer.cpp.o
.PHONY : src/DataVisualizer.cpp.o

src/DataVisualizer.i: src/DataVisualizer.cpp.i

.PHONY : src/DataVisualizer.i

# target to preprocess a source file
src/DataVisualizer.cpp.i:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataVisualizer.cpp.i
.PHONY : src/DataVisualizer.cpp.i

src/DataVisualizer.s: src/DataVisualizer.cpp.s

.PHONY : src/DataVisualizer.s

# target to generate assembly for a file
src/DataVisualizer.cpp.s:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/DataVisualizer.cpp.s
.PHONY : src/DataVisualizer.cpp.s

src/Plot.o: src/Plot.cpp.o

.PHONY : src/Plot.o

# target to build an object file
src/Plot.cpp.o:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/Plot.cpp.o
.PHONY : src/Plot.cpp.o

src/Plot.i: src/Plot.cpp.i

.PHONY : src/Plot.i

# target to preprocess a source file
src/Plot.cpp.i:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/Plot.cpp.i
.PHONY : src/Plot.cpp.i

src/Plot.s: src/Plot.cpp.s

.PHONY : src/Plot.s

# target to generate assembly for a file
src/Plot.cpp.s:
	$(MAKE) -f CMakeFiles/Template.dir/build.make CMakeFiles/Template.dir/src/Plot.cpp.s
.PHONY : src/Plot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Template"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... src/Basic2DLinePlot.o"
	@echo "... src/Basic2DLinePlot.i"
	@echo "... src/Basic2DLinePlot.s"
	@echo "... src/DataSet.o"
	@echo "... src/DataSet.i"
	@echo "... src/DataSet.s"
	@echo "... src/DataSets.o"
	@echo "... src/DataSets.i"
	@echo "... src/DataSets.s"
	@echo "... src/DataVisualizer.o"
	@echo "... src/DataVisualizer.i"
	@echo "... src/DataVisualizer.s"
	@echo "... src/Plot.o"
	@echo "... src/Plot.i"
	@echo "... src/Plot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

